# Rime settings
# encoding: utf-8
# by: 空山明月
# date: 2024-05-27

config_version: '2.1'

schema_list:
  - {schema: wubi}
  - {schema: wb_spelling}
  - {schema: double_pinyin_flypy}

switcher:
  hotkeys:
    - Control+grave
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Caps_Lock: commit_code
    Eisu_toggle: noop
