description:
  color_name: default
  display_name: 默认
  create_time: 2024-04-26 14:15:16
  update_time: 2024-04-26 14:15:16
  is_template: true
style:
  color_scheme: default
  font_face: Microsoft YaHei
  label_font_face: Microsoft YaHei
  comment_font_face: 黑体字根
  font_point: 14
  label_font_point: 14
  comment_font_point: 13
  horizontal: false
  fullscreen: false
  inline_preedit: false
  preedit_type: composition
  display_tray_icon: false
  label_format: "%s."
  mark_text: ""
  vertical_auto_reverse: false
  vertical_text: false
  vertical_text_left_to_right: false
  vertical_text_with_wrap: false
  layout:
    align_type: center
    max_width: 0	
    min_width: 0
    min_height: 0
    max_height: 0	
    border_width: 2
    margin_x: 5
    margin_y: 5
    spacing: 5
    candidate_spacing: 8
    hilite_spacing: 8
    hilite_padding: 8
    round_corner: 10 
    corner_radius: 10
    shadow_radius: 0
    shadow_offset_x: 2
    shadow_offset_y: 2

preset_color_schemes:
  default:
    name: 默认
    author: 中书君
    text_color: 0x000000
    back_color: 0xffffff
    border_color: 0x000000
    hilited_text_color: 0x000000
    hilited_back_color: 0xdddddd
    hilited_candidate_text_color: 0xffffff
    hilited_candidate_back_color: 0x000000